name: download

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: | 
            npm i
            npm run build
            
      - name: download youtube video
        uses: ahaoboy/download-youtube-video@v3.0.0
        with:
          url: https://www.youtube.com/watch?v=nn9jdwEkplc


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
